language: ruby
rvm:
  - 2.3.4
notifications:
  email:
    - jani.jegoroff@gmail.com
before_install:
  - cd api
install:
  - bundle install --retry=3
script:
  - bundle exec rake test
  - bundle exec rake rubocop
