source 'https://rubygems.org'

gem 'cucumber', '~> 3.0'
gem 'rake', '~> 12.2'
gem 'rspec', '~> 3.7'
gem 'selenium-webdriver', '~> 3.7'

gem 'rubocop', '~> 0.51'
gem 'rubocop-checkstyle_formatter', '~> 0.3'
