# require 'rake/testtask'
require 'rubocop/rake_task'
require 'cucumber/rake/task'

task default: %i[cucumber rubocop]

desc 'Run tests'
Cucumber::Rake::Task.new(:cucumber) do |t|
  t.cucumber_opts = 'features --format pretty'
end

desc 'Execute RuboCop static code analysis'
RuboCop::RakeTask.new(:rubocop) do |t|
  t.options = %w[-D]
  t.fail_on_error = true
end
